project_name: abb_ia
before:
  hooks:
    - go mod download
    - go mod tidy
    - go test -v ./...
builds:
  - id: default
    main: ./main.go
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: abb_ia

release:
  ids: [ default ]
  draft: true
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"
  prerelease: auto
  mode: replace
  header: |
    ## ⚙️ The `{{ .Tag }}` release
  footer: |
    ## Install from binaries
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files: [ LICENSE.txt, README.md ]
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
signs:
  - cmd: gpg
    args:
      - --output
      - $signature
      - --detach-sig
      - $artifact
    signature: ${artifact}.sig
    artifacts: none
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^conf:'